//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockolate.Migration.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mockolate.Migration.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate Moq to Mockolate.
        /// </summary>
        internal static string MockolateM001CodeFixTitle {
            get {
                return ResourceManager.GetString("MockolateM001CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate the mocks from Moq to Mockolate..
        /// </summary>
        internal static string MockolateM001Description {
            get {
                return ResourceManager.GetString("MockolateM001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moq should be migrated to Mockolate..
        /// </summary>
        internal static string MockolateM001MessageFormat {
            get {
                return ResourceManager.GetString("MockolateM001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moq should be migrated..
        /// </summary>
        internal static string MockolateM001Title {
            get {
                return ResourceManager.GetString("MockolateM001Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Migrate NSubstitute to Mockolate.
        /// </summary>
        internal static string MockolateM002CodeFixTitle {
            get {
                return ResourceManager.GetString("MockolateM002CodeFixTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Migrate the mocks from NSubstitute to Mockolate..
        /// </summary>
        internal static string MockolateM002Description {
            get {
                return ResourceManager.GetString("MockolateM002Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NSubstitute should be migrated to Mockolate..
        /// </summary>
        internal static string MockolateM002MessageFormat {
            get {
                return ResourceManager.GetString("MockolateM002MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NSubstitute should be migrated..
        /// </summary>
        internal static string MockolateM002Title {
            get {
                return ResourceManager.GetString("MockolateM002Title", resourceCulture);
            }
        }
    }
}
